
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 15;
  public static final int MayorI = 17;
  public static final int DeclareE = 7;
  public static final int Coma = 32;
  public static final int PuntoC = 33;
  public static final int DeclareB = 6;
  public static final int If = 3;
  public static final int LlaveC = 29;
  public static final int Real = 38;
  public static final int LlaveA = 28;
  public static final int VarId = 35;
  public static final int Menor = 18;
  public static final int Else = 4;
  public static final int PInt = 11;
  public static final int Asignacion = 34;
  public static final int Mayor = 16;
  public static final int While = 2;
  public static final int Division = 25;
  public static final int MenorI = 19;
  public static final int Const_String = 36;
  public static final int EOF = 0;
  public static final int And = 14;
  public static final int CorcheteC = 31;
  public static final int error = 1;
  public static final int Distinto = 20;
  public static final int CorcheteA = 30;
  public static final int Print = 5;
  public static final int ParC = 27;
  public static final int ParA = 26;
  public static final int PFloat = 12;
  public static final int Resta = 23;
  public static final int InList = 10;
  public static final int Multiplicacion = 24;
  public static final int ProgramE = 9;
  public static final int Numero = 37;
  public static final int Suma = 22;
  public static final int ProgramB = 8;
  public static final int PString = 13;
  public static final int Igual = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "While",
  "If",
  "Else",
  "Print",
  "DeclareB",
  "DeclareE",
  "ProgramB",
  "ProgramE",
  "InList",
  "PInt",
  "PFloat",
  "PString",
  "And",
  "Or",
  "Mayor",
  "MayorI",
  "Menor",
  "MenorI",
  "Distinto",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "ParA",
  "ParC",
  "LlaveA",
  "LlaveC",
  "CorcheteA",
  "CorcheteC",
  "Coma",
  "PuntoC",
  "Asignacion",
  "VarId",
  "Const_String",
  "Numero",
  "Real"
  };
}

